#[terminal.shell]
#program = "/home/eikku/bin/alacritty_tmux.sh"

[window]
padding.x = 0
padding.y = 0
dynamic_title = true
opacity = 0.8

[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"
size = 12.0

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black   = "#15161e"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

[colors.cursor]
text = "#1a1b26"
cursor = "#c0caf5"


[colors.selection]
text = "#1a1b26"
background = "#364a82"

[colors.search]
matches.background = "#3d59a1"
matches.foreground = "#c0caf5"


#focused_match.background = "#7aa2f7"

focused_match.foreground = "#1a1b26"
