set -g status-left "#{?client_prefix,#[reverse][prefix]#[noreverse]}"
set -g status-left-length 10
set -g status-right "#(~/bin/tmux-status-right.sh '#S')"
set -g status-justify left
set -g status-style 'fg=blue bg=default'
set -g base-index 1

setw -g window-status-separator "#[fg=white]|"

setw -g window-status-current-style "fg=blue bg=default"
setw -g window-status-current-format " #I #W #F "

setw -g window-status-style "fg=#565f89 bg=default"
setw -g window-status-format " #I #{fg=white}#W #F "

set -g pane-active-border-style 'fg=blue'
set -g pane-border-style 'fg=blue,dim'

set-option -g exit-empty on
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*:Tc"
set-option -g set-clipboard on

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

setw -g mouse on

bind r source-file ~/.tmux.conf

bind '"' split-window -v -c "#{pane_current_path}"
bind '#' split-window -h -c "#{pane_current_path}"

bind e display-popup -d "#{pane_current_path}"

bind tab select-layout even-vertical

is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?\.?(view|n?vim?x?)(-wrapped)?(diff)?$'"

# navigation (handled by sway and neovim)
#bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}' '' 'select-pane -L' }
#bind-key -n 'C-j' if-shell "$is_vim" "send-keys C-j" { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
#bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}' '' 'select-pane -U' }
#bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}' '' 'select-pane -R' }
#bind-key -n 'C-n' if-shell "$is_vim" 'send-keys C-n' { if -F '#{window_end_flag}' '' 'select-window -n' }

# resize
bind -n 'C-M-h' if-shell "$is_vim" 'send-keys C-M-h' 'resize-pane -L 1'
bind -n 'C-M-j' if-shell "$is_vim" 'send-keys C-M-j' 'resize-pane -D 1'
bind -n 'C-M-k' if-shell "$is_vim" 'send-keys C-M-k' 'resize-pane -U 1'
bind -n 'C-M-l' if-shell "$is_vim" 'send-keys C-M-l' 'resize-pane -R 1'

# swap
bind 'h' if-shell "$is_vim" 'send-keys zh' 'swap-pane -s "{left-of}"'
bind 'j' if-shell "$is_vim" 'send-keys zj' 'swap-pane -s "{down-of}"'
bind 'k' if-shell "$is_vim" 'send-keys zk' 'swap-pane -s "{up-of}"'
bind 'l' if-shell "$is_vim" 'send-keys zl' 'swap-pane -s "{right-of}"'
